name: Terraform Lambda Deployment

on:
  workflow_dispatch:
    inputs:
      upload_new_image:
        description: "Upload new deployment image?"
        required: true
        default: "false"
      deployment_image_path:
        description: "Path to local image (if uploading new one)"
        required: false
  push:
    branches:
      - deploy

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # your Terraform directory

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: List Terraform folder
        run: ls -l ./Terraform-lambda-api

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Upload new image (optional)
        if: ${{ github.event.inputs.upload_new_image == 'true' }}
        run: |
          echo "Uploading new deployment image..."
          aws s3 cp "${{ github.event.inputs.deployment_image_path }}" "s3://deploybucket9466901628/deployment.png" --acl private

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false \
          -var="upload_new_image=${{ github.event.inputs.upload_new_image }}" \
          -var="deployment_image_path=${{ github.event.inputs.deployment_image_path }}"
